class IncomeStatement(object):
    netincometocommon = 'netincometocommon'
    dilutedeps = 'dilutedeps'
    netinterestincome = 'netinterestincome'
    otheradjustmentstonetincometocommon = 'otheradjustmentstonetincometocommon'
    basiceps = 'basiceps'
    nonoperatingincome = 'nonoperatingincome'
    othergains = 'othergains'
    netincomecontinuing = 'netincomecontinuing'
    totaloperatingincome = 'totaloperatingincome'
    preferreddividends = 'preferreddividends'
    netincome = 'netincome'
    policyacquisitioncosts = 'policyacquisitioncosts'
    totalcostofrevenue = 'totalcostofrevenue'
    totalinterestexpense = 'totalinterestexpense'
    othernoninterestincome = 'othernoninterestincome'
    impairmentexpense = 'impairmentexpense'
    totalrevenue = 'totalrevenue'
    otheroperatingexpenses = 'otheroperatingexpenses'
    propertyliabilityinsuranceclaims = 'propertyliabilityinsuranceclaims'
    restructuringcharge = 'restructuringcharge'
    investmentsecuritiesinterestincome = 'investmentsecuritiesinterestincome'
    depositsinterestexpense = 'depositsinterestexpense'
    cashdividendspershare = 'cashdividendspershare'
    totaloperatingexpenses = 'totaloperatingexpenses'
    premiumsearned = 'premiumsearned'
    fedfundsandrepointerestincome = 'fedfundsandrepointerestincome'
    otheradjustmentstoconsolidatednetincome = 'otheradjustmentstoconsolidatednetincome'
    extraordinaryincome = 'extraordinaryincome'
    weightedavebasicsharesos = 'weightedavebasicsharesos'
    loansandleaseinterestincome = 'loansandleaseinterestincome'
    otherinterestincome = 'otherinterestincome'
    trustfeeincome = 'trustfeeincome'
    totalnoninterestincome = 'totalnoninterestincome'
    fedfundsandrepointerestexpense = 'fedfundsandrepointerestexpense'
    rdexpense = 'rdexpense'
    totalgrossprofit = 'totalgrossprofit'
    weightedavebasicdilutedsharesos = 'weightedavebasicdilutedsharesos'
    investmentbankingincome = 'investmentbankingincome'
    tradingaccountinterestincome = 'tradingaccountinterestincome'
    netoccupancyequipmentexpense = 'netoccupancyequipmentexpense'
    servicechargesondepositsincome = 'servicechargesondepositsincome'
    explorationexpense = 'explorationexpense'
    otherservicechargeincome = 'otherservicechargeincome'
    operatingrevenue = 'operatingrevenue'
    otherincome = 'otherincome'
    otherrevenue = 'otherrevenue'
    otherinterestexpense = 'otherinterestexpense'
    incometaxexpense = 'incometaxexpense'
    weightedavedilutedsharesos = 'weightedavedilutedsharesos'
    currentandfuturebenefits = 'currentandfuturebenefits'
    basicdilutedeps = 'basicdilutedeps'
    longtermdebtinterestexpense = 'longtermdebtinterestexpense'
    operatingcostofrevenue = 'operatingcostofrevenue'
    netincometononcontrollinginterest = 'netincometononcontrollinginterest'
    totalotherincome = 'totalotherincome'
    amortizationexpense = 'amortizationexpense'
    totalinterestincome = 'totalinterestincome'
    salariesandemployeebenefitsexpense = 'salariesandemployeebenefitsexpense'
    shorttermborrowinginterestexpense = 'shorttermborrowinginterestexpense'
    depositsinterestincome = 'depositsinterestincome'
    amortizationofdeferredpolicyacquisitioncosts = 'amortizationofdeferredpolicyacquisitioncosts'
    totalpretaxincome = 'totalpretaxincome'
    netincomediscontinued = 'netincomediscontinued'
    totalnoninterestexpense = 'totalnoninterestexpense'
    depletionexpense = 'depletionexpense'
    depreciationexpense = 'depreciationexpense'
    provisionforcreditlosses = 'provisionforcreditlosses'
    othercostofrevenue = 'othercostofrevenue'
    otherspecialcharges = 'otherspecialcharges'
    marketingexpense = 'marketingexpense'
    netrealizedcapitalgains = 'netrealizedcapitalgains'
    sgaexpense = 'sgaexpense'


class BalanceSheet(object):
    prepaidexpenses = 'prepaidexpenses'
    commonequity = 'commonequity'
    interestbearingdepositsatotherbanks = 'interestbearingdepositsatotherbanks'
    policyholderfunds = 'policyholderfunds'
    noncurrentdeferredtaxliabilities = 'noncurrentdeferredtaxliabilities'
    totalcommonequity = 'totalcommonequity'
    unearnedpremiumscredit = 'unearnedpremiumscredit'
    totalnoncurrentliabilities = 'totalnoncurrentliabilities'
    currentemployeebenefitliabilities = 'currentemployeebenefitliabilities'
    noncurrentnotereceivables = 'noncurrentnotereceivables'
    totalcurrentliabilities = 'totalcurrentliabilities'
    commitmentsandcontingencies = 'commitmentsandcontingencies'
    otherequity = 'otherequity'
    redeemablenoncontrollinginterest = 'redeemablenoncontrollinginterest'
    futurepolicybenefits = 'futurepolicybenefits'
    totalliabilitiesandequity = 'totalliabilitiesandequity'
    netinventory = 'netinventory'
    noncontrollinginterests = 'noncontrollinginterests'
    totalequityandnoncontrollinginterests = 'totalequityandnoncontrollinginterests'
    otherlongtermliabilities = 'otherlongtermliabilities'
    shorttermdebt = 'shorttermdebt'
    shortterminvestments = 'shortterminvestments'
    noncurrentdeferredrevenue = 'noncurrentdeferredrevenue'
    accruedinvestmentincome = 'accruedinvestmentincome'
    fedfundssold = 'fedfundssold'
    accruedexpenses = 'accruedexpenses'
    othernoncurrentnonoperatingassets = 'othernoncurrentnonoperatingassets'
    assetretirementandlitigationobligation = 'assetretirementandlitigationobligation'
    longterminvestments = 'longterminvestments'
    separateaccountbusinessliabilities = 'separateaccountbusinessliabilities'
    loansheldforsale = 'loansheldforsale'
    netppe = 'netppe'
    totalnoncurrentassets = 'totalnoncurrentassets'
    currentdeferredtaxassets = 'currentdeferredtaxassets'
    netpremisesandequipment = 'netpremisesandequipment'
    totalequity = 'totalequity'
    netloansandleases = 'netloansandleases'
    totalpreferredequity = 'totalpreferredequity'
    dividendspayable = 'dividendspayable'
    othernoncurrentassets = 'othernoncurrentassets'
    separateaccountbusinessassets = 'separateaccountbusinessassets'
    othercurrentassets = 'othercurrentassets'
    allowanceforloanandleaselosses = 'allowanceforloanandleaselosses'
    retainedearnings = 'retainedearnings'
    currentdeferredtaxliabilities = 'currentdeferredtaxliabilities'
    claimsandclaimexpenses = 'claimsandclaimexpenses'
    capitalleaseobligations = 'capitalleaseobligations'
    noninterestbearingdeposits = 'noninterestbearingdeposits'
    fedfundspurchased = 'fedfundspurchased'
    notereceivable = 'notereceivable'
    grossppe = 'grossppe'
    mortgageservicingrights = 'mortgageservicingrights'
    tradingaccountsecurities = 'tradingaccountsecurities'
    currentdeferredrevenue = 'currentdeferredrevenue'
    unearnedpremiumsdebit = 'unearnedpremiumsdebit'
    interestbearingdeposits = 'interestbearingdeposits'
    accountsreceivable = 'accountsreceivable'
    accruedinterestpayable = 'accruedinterestpayable'
    accountspayable = 'accountspayable'
    timedepositsplaced = 'timedepositsplaced'
    noncurrentdeferredtaxassets = 'noncurrentdeferredtaxassets'
    deferredacquisitioncost = 'deferredacquisitioncost'
    othernoncurrentliabilities = 'othernoncurrentliabilities'
    othercurrentnonoperatingassets = 'othercurrentnonoperatingassets'
    treasurystock = 'treasurystock'
    restrictedcash = 'restrictedcash'
    othertaxespayable = 'othertaxespayable'
    customerandotherreceivables = 'customerandotherreceivables'
    aoci = 'aoci'
    isna = 'isna'
    participatingpolicyholderequity = 'participatingpolicyholderequity'
    otherassets = 'otherassets'
    noncurrentemployeebenefitliabilities = 'noncurrentemployeebenefitliabilities'
    intangibleassets = 'intangibleassets'
    longtermdebt = 'longtermdebt'
    othernoncurrentnonoperatingliabilities = 'othernoncurrentnonoperatingliabilities'
    loansandleases = 'loansandleases'
    totalassets = 'totalassets'
    goodwill = 'goodwill'
    othercurrentliabilities = 'othercurrentliabilities'
    customerdeposits = 'customerdeposits'
    accumulateddepreciation = 'accumulateddepreciation'
    othercurrentnonoperatingliabilities = 'othercurrentnonoperatingliabilities'
    othershorttermpayables = 'othershorttermpayables'
    totalliabilities = 'totalliabilities'
    employeebenefitassets = 'employeebenefitassets'
    totalcurrentassets = 'totalcurrentassets'
    bankersacceptances = 'bankersacceptances'
    cashandequivalents = 'cashandequivalents'


class CashFlowStatement(object):
    divestitures = 'divestitures'
    purchaseofinvestments = 'purchaseofinvestments'
    acquisitions = 'acquisitions'
    cashinterestreceived = 'cashinterestreceived'
    issuanceofdebt = 'issuanceofdebt'
    othergains = 'othergains'
    netincomecontinuing = 'netincomecontinuing'
    scfna = 'scfna'
    netcashfromdiscontinuedoperatingactivities = 'netcashfromdiscontinuedoperatingactivities'
    purchaseofplantpropertyandequipment = 'purchaseofplantpropertyandequipment'
    noncashadjustmentstonetincome = 'noncashadjustmentstonetincome'
    netincome = 'netincome'
    netchangeincash = 'netchangeincash'
    otherinvestingactivitiesnet = 'otherinvestingactivitiesnet'
    repaymentofdebt = 'repaymentofdebt'
    netcashfromdiscontinuedfinancingactivities = 'netcashfromdiscontinuedfinancingactivities'
    cashincometaxespaid = 'cashincometaxespaid'
    netcashfromcontinuingfinancingactivities = 'netcashfromcontinuingfinancingactivities'
    saleofinvestments = 'saleofinvestments'
    repurchaseofcommonequity = 'repurchaseofcommonequity'
    repurchaseofpreferredequity = 'repurchaseofpreferredequity'
    netcashfromcontinuinginvestingactivities = 'netcashfromcontinuinginvestingactivities'
    issuanceofpreferredequity = 'issuanceofpreferredequity'
    amortizationexpense = 'amortizationexpense'
    netcashfromoperatingactivities = 'netcashfromoperatingactivities'
    isna = 'isna'
    otherfinancingactivitiesnet = 'otherfinancingactivitiesnet'
    provisionforloanlosses = 'provisionforloanlosses'
    netcashfromdiscontinuedinvestingactivities = 'netcashfromdiscontinuedinvestingactivities'
    netcashfrominvestingactivities = 'netcashfrominvestingactivities'
    netincreaseinfedfundssold = 'netincreaseinfedfundssold'
    increasedecreaseinoperatingcapital = 'increasedecreaseinoperatingcapital'
    paymentofdividends = 'paymentofdividends'
    issuanceofcommonequity = 'issuanceofcommonequity'
    netchangeindeposits = 'netchangeindeposits'
    cashinterestpaid = 'cashinterestpaid'
    saleofplantpropertyandequipment = 'saleofplantpropertyandequipment'
    netincomediscontinued = 'netincomediscontinued'
    depreciationexpense = 'depreciationexpense'
    netcashfromcontinuingoperatingactivities = 'netcashfromcontinuingoperatingactivities'
    effectofexchangeratechanges = 'effectofexchangeratechanges'
    othernetchangesincash = 'othernetchangesincash'
    netcashfromfinancingactivities = 'netcashfromfinancingactivities'


class Calculations(object):
    ltdebtandcapleases = 'ltdebtandcapleases'
    divpayoutratio = 'divpayoutratio'
    investedcapital = 'investedcapital'
    revenuegrowth = 'revenuegrowth'
    ocftocapex = 'ocftocapex'
    fcffqoqgrowth = 'fcffqoqgrowth'
    croic = 'croic'
    opextorevenue = 'opextorevenue'
    ocflesscapextointerestex = 'ocflesscapextointerestex'
    revenueqoqgrowth = 'revenueqoqgrowth'
    ltdebttonopat = 'ltdebttonopat'
    efftaxrate = 'efftaxrate'
    epsqoqgrowth = 'epsqoqgrowth'
    nopatqoqgrowth = 'nopatqoqgrowth'
    roa = 'roa'
    dso = 'dso'
    dividendyield = 'dividendyield'
    commontocap = 'commontocap'
    epsgrowth = 'epsgrowth'
    normalizednopat = 'normalizednopat'
    pretaxincomemargin = 'pretaxincomemargin'
    ltdebttoequity = 'ltdebttoequity'
    ebitda = 'ebitda'
    normalizednopatmargin = 'normalizednopatmargin'
    assetturnover = 'assetturnover'
    nwc = 'nwc'
    augmentedpayoutratio = 'augmentedpayoutratio'
    ocfqoqgrowth = 'ocfqoqgrowth'
    pricetobook = 'pricetobook'
    dfnwc = 'dfnwc'
    roe = 'roe'
    totalcapital = 'totalcapital'
    ocfgrowth = 'ocfgrowth'
    fcffgrowth = 'fcffgrowth'
    invturnover = 'invturnover'
    preferredtocap = 'preferredtocap'
    freecashflow = 'freecashflow'
    ebitlesscapextointerestex = 'ebitlesscapextointerestex'
    nopat = 'nopat'
    netdebttonopat = 'netdebttonopat'
    tangbookvaluepershare = 'tangbookvaluepershare'
    ebittointerestex = 'ebittointerestex'
    dpo = 'dpo'
    roce = 'roce'
    taxburdenpct = 'taxburdenpct'
    costofrevtorevenue = 'costofrevtorevenue'
    netdebt = 'netdebt'
    nopatlesscapextointex = 'nopatlesscapextointex'
    evtoebitda = 'evtoebitda'
    ebitqoqgrowth = 'ebitqoqgrowth'
    pricetotangiblebook = 'pricetotangiblebook'
    debttoebitda = 'debttoebitda'
    investedcapitalgrowth = 'investedcapitalgrowth'
    ebitdamargin = 'ebitdamargin'
    evtoebit = 'evtoebit'
    ocftointerestex = 'ocftointerestex'
    bookvaluepershare = 'bookvaluepershare'
    roicnnepspread = 'roicnnepspread'
    evtonopat = 'evtonopat'
    roic = 'roic'
    profitmargin = 'profitmargin'
    nopattointerestex = 'nopattointerestex'
    investedcapitalincreasedecrease = 'investedcapitalincreasedecrease'
    nnep = 'nnep'
    rnnoa = 'rnnoa'
    evtorevenue = 'evtorevenue'
    ccc = 'ccc'
    ebitmargin = 'ebitmargin'
    debt = 'debt'
    oroa = 'oroa'
    marketcap = 'marketcap'
    evtoinvestedcapital = 'evtoinvestedcapital'
    sgaextorevenue = 'sgaextorevenue'
    ebitdaqoqgrowth = 'ebitdaqoqgrowth'
    capex = 'capex'
    debttototalcapital = 'debttototalcapital'
    nopatmargin = 'nopatmargin'
    debttoequity = 'debttoequity'
    investedcapitalturnover = 'investedcapitalturnover'
    netincomegrowth = 'netincomegrowth'
    noncontrolinttocap = 'noncontrolinttocap'
    evtoocf = 'evtoocf'
    investedcapitalqoqgrowth = 'investedcapitalqoqgrowth'
    noncontrollinginterestsharingratio = 'noncontrollinginterestsharingratio'
    debttonopat = 'debttonopat'
    dfcfnwc = 'dfcfnwc'
    dio = 'dio'
    netincomeqoqgrowth = 'netincomeqoqgrowth'
    ebitdagrowth = 'ebitdagrowth'
    operatingmargin = 'operatingmargin'
    arturnover = 'arturnover'
    stdebttocap = 'stdebttocap'
    depreciationandamortization = 'depreciationandamortization'
    enterprisevalue = 'enterprisevalue'
    nopatgrowth = 'nopatgrowth'
    ltdebttocap = 'ltdebttocap'
    interestburdenpct = 'interestburdenpct'
    compoundleveragefactor = 'compoundleveragefactor'
    grossmargin = 'grossmargin'
    pricetoearnings = 'pricetoearnings'
    faturnover = 'faturnover'
    evtofcff = 'evtofcff'
    netdebttoebitda = 'netdebttoebitda'
    netnonopex = 'netnonopex'
    leverageratio = 'leverageratio'
    earningsyield = 'earningsyield'
    ltdebttoebitda = 'ltdebttoebitda'
    ebit = 'ebit'
    ebitgrowth = 'ebitgrowth'
    pricetorevenue = 'pricetorevenue'
    rdextorevenue = 'rdextorevenue'
    apturnover = 'apturnover'
    netnonopobligations = 'netnonopobligations'
    finleverage = 'finleverage'


class Tags(object):
    positions = 'positions'
    symbol = 'symbol'
    year = 'year'
    quarter = 'quarter'
    rep_period = 'rep_period'
    next_rep_period = 'next_rep_period'
    current_date = 'date'
    prev_date = 'prev_date'
    next_date = 'next_date'
    t_curr_half_mean = 't: curr_half_mean'
    t_curr_month_mean = 't: curr_month_mean'
    t_curr_period_mean = 't: curr_period_mean'
    price = 'price'
    next_price = 'next_price'
    shareprice = 't: current_price'
    increase = 't: daily_increase'
    t_half_month_increase = 't: half_month_increase'
    t_monthly_increase = 't: monthly_increase'
    t_next_half_mean = 't: next_half_mean'
    t_next_month_mean = 't: next_month_mean'
    t_next_period_mean = 't: next_period_mean'
    t_next_price = 't: next_price'
    t_period_increase = 't: period_increase'
    netincometocommon = 'netincometocommon'
    dilutedeps = 'dilutedeps'
    netinterestincome = 'netinterestincome'
    otheradjustmentstonetincometocommon = 'otheradjustmentstonetincometocommon'
    basiceps = 'basiceps'
    nonoperatingincome = 'nonoperatingincome'
    othergains = 'othergains'
    netincomecontinuing = 'netincomecontinuing'
    totaloperatingincome = 'totaloperatingincome'
    preferreddividends = 'preferreddividends'
    netincome = 'netincome'
    policyacquisitioncosts = 'policyacquisitioncosts'
    totalcostofrevenue = 'totalcostofrevenue'
    totalinterestexpense = 'totalinterestexpense'
    othernoninterestincome = 'othernoninterestincome'
    impairmentexpense = 'impairmentexpense'
    totalrevenue = 'totalrevenue'
    otheroperatingexpenses = 'otheroperatingexpenses'
    propertyliabilityinsuranceclaims = 'propertyliabilityinsuranceclaims'
    restructuringcharge = 'restructuringcharge'
    investmentsecuritiesinterestincome = 'investmentsecuritiesinterestincome'
    depositsinterestexpense = 'depositsinterestexpense'
    cashdividendspershare = 'cashdividendspershare'
    totaloperatingexpenses = 'totaloperatingexpenses'
    premiumsearned = 'premiumsearned'
    fedfundsandrepointerestincome = 'fedfundsandrepointerestincome'
    otheradjustmentstoconsolidatednetincome = 'otheradjustmentstoconsolidatednetincome'
    extraordinaryincome = 'extraordinaryincome'
    weightedavebasicsharesos = 'weightedavebasicsharesos'
    loansandleaseinterestincome = 'loansandleaseinterestincome'
    otherinterestincome = 'otherinterestincome'
    trustfeeincome = 'trustfeeincome'
    totalnoninterestincome = 'totalnoninterestincome'
    fedfundsandrepointerestexpense = 'fedfundsandrepointerestexpense'
    rdexpense = 'rdexpense'
    totalgrossprofit = 'totalgrossprofit'
    weightedavebasicdilutedsharesos = 'weightedavebasicdilutedsharesos'
    investmentbankingincome = 'investmentbankingincome'
    tradingaccountinterestincome = 'tradingaccountinterestincome'
    netoccupancyequipmentexpense = 'netoccupancyequipmentexpense'
    servicechargesondepositsincome = 'servicechargesondepositsincome'
    explorationexpense = 'explorationexpense'
    otherservicechargeincome = 'otherservicechargeincome'
    operatingrevenue = 'operatingrevenue'
    otherincome = 'otherincome'
    otherrevenue = 'otherrevenue'
    otherinterestexpense = 'otherinterestexpense'
    incometaxexpense = 'incometaxexpense'
    weightedavedilutedsharesos = 'weightedavedilutedsharesos'
    currentandfuturebenefits = 'currentandfuturebenefits'
    basicdilutedeps = 'basicdilutedeps'
    longtermdebtinterestexpense = 'longtermdebtinterestexpense'
    operatingcostofrevenue = 'operatingcostofrevenue'
    netincometononcontrollinginterest = 'netincometononcontrollinginterest'
    totalotherincome = 'totalotherincome'
    amortizationexpense = 'amortizationexpense'
    totalinterestincome = 'totalinterestincome'
    salariesandemployeebenefitsexpense = 'salariesandemployeebenefitsexpense'
    shorttermborrowinginterestexpense = 'shorttermborrowinginterestexpense'
    depositsinterestincome = 'depositsinterestincome'
    amortizationofdeferredpolicyacquisitioncosts = 'amortizationofdeferredpolicyacquisitioncosts'
    totalpretaxincome = 'totalpretaxincome'
    netincomediscontinued = 'netincomediscontinued'
    totalnoninterestexpense = 'totalnoninterestexpense'
    depletionexpense = 'depletionexpense'
    depreciationexpense = 'depreciationexpense'
    provisionforcreditlosses = 'provisionforcreditlosses'
    othercostofrevenue = 'othercostofrevenue'
    otherspecialcharges = 'otherspecialcharges'
    marketingexpense = 'marketingexpense'
    netrealizedcapitalgains = 'netrealizedcapitalgains'
    sgaexpense = 'sgaexpense'
    prepaidexpenses = 'prepaidexpenses'
    commonequity = 'commonequity'
    interestbearingdepositsatotherbanks = 'interestbearingdepositsatotherbanks'
    policyholderfunds = 'policyholderfunds'
    noncurrentdeferredtaxliabilities = 'noncurrentdeferredtaxliabilities'
    totalcommonequity = 'totalcommonequity'
    unearnedpremiumscredit = 'unearnedpremiumscredit'
    totalnoncurrentliabilities = 'totalnoncurrentliabilities'
    currentemployeebenefitliabilities = 'currentemployeebenefitliabilities'
    noncurrentnotereceivables = 'noncurrentnotereceivables'
    totalcurrentliabilities = 'totalcurrentliabilities'
    commitmentsandcontingencies = 'commitmentsandcontingencies'
    otherequity = 'otherequity'
    redeemablenoncontrollinginterest = 'redeemablenoncontrollinginterest'
    futurepolicybenefits = 'futurepolicybenefits'
    totalliabilitiesandequity = 'totalliabilitiesandequity'
    netinventory = 'netinventory'
    noncontrollinginterests = 'noncontrollinginterests'
    totalequityandnoncontrollinginterests = 'totalequityandnoncontrollinginterests'
    otherlongtermliabilities = 'otherlongtermliabilities'
    shorttermdebt = 'shorttermdebt'
    shortterminvestments = 'shortterminvestments'
    noncurrentdeferredrevenue = 'noncurrentdeferredrevenue'
    accruedinvestmentincome = 'accruedinvestmentincome'
    fedfundssold = 'fedfundssold'
    accruedexpenses = 'accruedexpenses'
    othernoncurrentnonoperatingassets = 'othernoncurrentnonoperatingassets'
    assetretirementandlitigationobligation = 'assetretirementandlitigationobligation'
    longterminvestments = 'longterminvestments'
    separateaccountbusinessliabilities = 'separateaccountbusinessliabilities'
    loansheldforsale = 'loansheldforsale'
    netppe = 'netppe'
    totalnoncurrentassets = 'totalnoncurrentassets'
    currentdeferredtaxassets = 'currentdeferredtaxassets'
    netpremisesandequipment = 'netpremisesandequipment'
    totalequity = 'totalequity'
    netloansandleases = 'netloansandleases'
    totalpreferredequity = 'totalpreferredequity'
    dividendspayable = 'dividendspayable'
    othernoncurrentassets = 'othernoncurrentassets'
    separateaccountbusinessassets = 'separateaccountbusinessassets'
    othercurrentassets = 'othercurrentassets'
    allowanceforloanandleaselosses = 'allowanceforloanandleaselosses'
    retainedearnings = 'retainedearnings'
    currentdeferredtaxliabilities = 'currentdeferredtaxliabilities'
    claimsandclaimexpenses = 'claimsandclaimexpenses'
    capitalleaseobligations = 'capitalleaseobligations'
    noninterestbearingdeposits = 'noninterestbearingdeposits'
    fedfundspurchased = 'fedfundspurchased'
    notereceivable = 'notereceivable'
    grossppe = 'grossppe'
    mortgageservicingrights = 'mortgageservicingrights'
    tradingaccountsecurities = 'tradingaccountsecurities'
    currentdeferredrevenue = 'currentdeferredrevenue'
    unearnedpremiumsdebit = 'unearnedpremiumsdebit'
    interestbearingdeposits = 'interestbearingdeposits'
    accountsreceivable = 'accountsreceivable'
    accruedinterestpayable = 'accruedinterestpayable'
    accountspayable = 'accountspayable'
    timedepositsplaced = 'timedepositsplaced'
    noncurrentdeferredtaxassets = 'noncurrentdeferredtaxassets'
    deferredacquisitioncost = 'deferredacquisitioncost'
    othernoncurrentliabilities = 'othernoncurrentliabilities'
    othercurrentnonoperatingassets = 'othercurrentnonoperatingassets'
    treasurystock = 'treasurystock'
    restrictedcash = 'restrictedcash'
    othertaxespayable = 'othertaxespayable'
    customerandotherreceivables = 'customerandotherreceivables'
    aoci = 'aoci'
    isna = 'isna'
    participatingpolicyholderequity = 'participatingpolicyholderequity'
    otherassets = 'otherassets'
    noncurrentemployeebenefitliabilities = 'noncurrentemployeebenefitliabilities'
    intangibleassets = 'intangibleassets'
    longtermdebt = 'longtermdebt'
    othernoncurrentnonoperatingliabilities = 'othernoncurrentnonoperatingliabilities'
    loansandleases = 'loansandleases'
    totalassets = 'totalassets'
    goodwill = 'goodwill'
    othercurrentliabilities = 'othercurrentliabilities'
    customerdeposits = 'customerdeposits'
    accumulateddepreciation = 'accumulateddepreciation'
    othercurrentnonoperatingliabilities = 'othercurrentnonoperatingliabilities'
    othershorttermpayables = 'othershorttermpayables'
    totalliabilities = 'totalliabilities'
    employeebenefitassets = 'employeebenefitassets'
    totalcurrentassets = 'totalcurrentassets'
    bankersacceptances = 'bankersacceptances'
    cashandequivalents = 'cashandequivalents'
    divestitures = 'divestitures'
    purchaseofinvestments = 'purchaseofinvestments'
    acquisitions = 'acquisitions'
    cashinterestreceived = 'cashinterestreceived'
    issuanceofdebt = 'issuanceofdebt'
    scfna = 'scfna'
    netcashfromdiscontinuedoperatingactivities = 'netcashfromdiscontinuedoperatingactivities'
    purchaseofplantpropertyandequipment = 'purchaseofplantpropertyandequipment'
    noncashadjustmentstonetincome = 'noncashadjustmentstonetincome'
    netchangeincash = 'netchangeincash'
    otherinvestingactivitiesnet = 'otherinvestingactivitiesnet'
    repaymentofdebt = 'repaymentofdebt'
    netcashfromdiscontinuedfinancingactivities = 'netcashfromdiscontinuedfinancingactivities'
    cashincometaxespaid = 'cashincometaxespaid'
    netcashfromcontinuingfinancingactivities = 'netcashfromcontinuingfinancingactivities'
    saleofinvestments = 'saleofinvestments'
    repurchaseofcommonequity = 'repurchaseofcommonequity'
    repurchaseofpreferredequity = 'repurchaseofpreferredequity'
    netcashfromcontinuinginvestingactivities = 'netcashfromcontinuinginvestingactivities'
    issuanceofpreferredequity = 'issuanceofpreferredequity'
    netcashfromoperatingactivities = 'netcashfromoperatingactivities'
    otherfinancingactivitiesnet = 'otherfinancingactivitiesnet'
    provisionforloanlosses = 'provisionforloanlosses'
    netcashfromdiscontinuedinvestingactivities = 'netcashfromdiscontinuedinvestingactivities'
    netcashfrominvestingactivities = 'netcashfrominvestingactivities'
    netincreaseinfedfundssold = 'netincreaseinfedfundssold'
    increasedecreaseinoperatingcapital = 'increasedecreaseinoperatingcapital'
    paymentofdividends = 'paymentofdividends'
    issuanceofcommonequity = 'issuanceofcommonequity'
    netchangeindeposits = 'netchangeindeposits'
    cashinterestpaid = 'cashinterestpaid'
    saleofplantpropertyandequipment = 'saleofplantpropertyandequipment'
    netcashfromcontinuingoperatingactivities = 'netcashfromcontinuingoperatingactivities'
    effectofexchangeratechanges = 'effectofexchangeratechanges'
    othernetchangesincash = 'othernetchangesincash'
    netcashfromfinancingactivities = 'netcashfromfinancingactivities'
    ltdebtandcapleases = 'ltdebtandcapleases'
    divpayoutratio = 'divpayoutratio'
    investedcapital = 'investedcapital'
    revenuegrowth = 'revenuegrowth'
    ocftocapex = 'ocftocapex'
    fcffqoqgrowth = 'fcffqoqgrowth'
    croic = 'croic'
    opextorevenue = 'opextorevenue'
    ocflesscapextointerestex = 'ocflesscapextointerestex'
    revenueqoqgrowth = 'revenueqoqgrowth'
    ltdebttonopat = 'ltdebttonopat'
    efftaxrate = 'efftaxrate'
    epsqoqgrowth = 'epsqoqgrowth'
    nopatqoqgrowth = 'nopatqoqgrowth'
    roa = 'roa'
    dso = 'dso'
    dividendyield = 'dividendyield'
    commontocap = 'commontocap'
    epsgrowth = 'epsgrowth'
    normalizednopat = 'normalizednopat'
    pretaxincomemargin = 'pretaxincomemargin'
    ltdebttoequity = 'ltdebttoequity'
    ebitda = 'ebitda'
    normalizednopatmargin = 'normalizednopatmargin'
    assetturnover = 'assetturnover'
    nwc = 'nwc'
    augmentedpayoutratio = 'augmentedpayoutratio'
    ocfqoqgrowth = 'ocfqoqgrowth'
    pricetobook = 'pricetobook'
    dfnwc = 'dfnwc'
    roe = 'roe'
    totalcapital = 'totalcapital'
    ocfgrowth = 'ocfgrowth'
    fcffgrowth = 'fcffgrowth'
    invturnover = 'invturnover'
    preferredtocap = 'preferredtocap'
    freecashflow = 'freecashflow'
    ebitlesscapextointerestex = 'ebitlesscapextointerestex'
    nopat = 'nopat'
    netdebttonopat = 'netdebttonopat'
    tangbookvaluepershare = 'tangbookvaluepershare'
    ebittointerestex = 'ebittointerestex'
    dpo = 'dpo'
    roce = 'roce'
    taxburdenpct = 'taxburdenpct'
    costofrevtorevenue = 'costofrevtorevenue'
    netdebt = 'netdebt'
    nopatlesscapextointex = 'nopatlesscapextointex'
    evtoebitda = 'evtoebitda'
    ebitqoqgrowth = 'ebitqoqgrowth'
    pricetotangiblebook = 'pricetotangiblebook'
    debttoebitda = 'debttoebitda'
    investedcapitalgrowth = 'investedcapitalgrowth'
    ebitdamargin = 'ebitdamargin'
    evtoebit = 'evtoebit'
    ocftointerestex = 'ocftointerestex'
    bookvaluepershare = 'bookvaluepershare'
    roicnnepspread = 'roicnnepspread'
    evtonopat = 'evtonopat'
    roic = 'roic'
    profitmargin = 'profitmargin'
    nopattointerestex = 'nopattointerestex'
    investedcapitalincreasedecrease = 'investedcapitalincreasedecrease'
    nnep = 'nnep'
    rnnoa = 'rnnoa'
    evtorevenue = 'evtorevenue'
    ccc = 'ccc'
    ebitmargin = 'ebitmargin'
    debt = 'debt'
    oroa = 'oroa'
    marketcap = 'marketcap'
    evtoinvestedcapital = 'evtoinvestedcapital'
    sgaextorevenue = 'sgaextorevenue'
    ebitdaqoqgrowth = 'ebitdaqoqgrowth'
    capex = 'capex'
    debttototalcapital = 'debttototalcapital'
    nopatmargin = 'nopatmargin'
    debttoequity = 'debttoequity'
    investedcapitalturnover = 'investedcapitalturnover'
    netincomegrowth = 'netincomegrowth'
    noncontrolinttocap = 'noncontrolinttocap'
    evtoocf = 'evtoocf'
    investedcapitalqoqgrowth = 'investedcapitalqoqgrowth'
    noncontrollinginterestsharingratio = 'noncontrollinginterestsharingratio'
    debttonopat = 'debttonopat'
    dfcfnwc = 'dfcfnwc'
    dio = 'dio'
    netincomeqoqgrowth = 'netincomeqoqgrowth'
    ebitdagrowth = 'ebitdagrowth'
    operatingmargin = 'operatingmargin'
    arturnover = 'arturnover'
    stdebttocap = 'stdebttocap'
    depreciationandamortization = 'depreciationandamortization'
    enterprisevalue = 'enterprisevalue'
    nopatgrowth = 'nopatgrowth'
    ltdebttocap = 'ltdebttocap'
    interestburdenpct = 'interestburdenpct'
    compoundleveragefactor = 'compoundleveragefactor'
    grossmargin = 'grossmargin'
    pricetoearnings = 'pricetoearnings'
    faturnover = 'faturnover'
    evtofcff = 'evtofcff'
    netdebttoebitda = 'netdebttoebitda'
    netnonopex = 'netnonopex'
    leverageratio = 'leverageratio'
    earningsyield = 'earningsyield'
    ltdebttoebitda = 'ltdebttoebitda'
    ebit = 'ebit'
    ebitgrowth = 'ebitgrowth'
    pricetorevenue = 'pricetorevenue'
    rdextorevenue = 'rdextorevenue'
    apturnover = 'apturnover'
    netnonopobligations = 'netnonopobligations'
    finleverage = 'finleverage'

    # CUSTOM TAGS
    dps2price = 'dividends/share2price'
    dividendspayoutratio = 'dividendpayoutratio'
    debtratio = 'debtratio'
    currentratio = 'currentratio'

    # book2market = 'booktomarket'
    # fcf2equity = 'fcf2equity'
    # fcf2commonequity = 'fcf2commonequity'
    # price2book = 'price2book'

    # income_statement = IncomeStatement
    # cash_flow_statement = CashFlowStatement
    # balance_sheet = BalanceSheet
    # calculations = Calculations

    income_statement = [attr for attr in dir(IncomeStatement) if
                        not attr.startswith('__')]
    cash_flow = [attr for attr in dir(CashFlowStatement) if
                 not attr.startswith('__')]
    balance_sheet = [attr for attr in dir(BalanceSheet) if
                     not attr.startswith('__')]
    calculations = [attr for attr in dir(Calculations) if
                    not attr.startswith('__')]

    @classmethod
    def basic_tags(cls):
        basic_tags = [cls.symbol,
                      cls.year,
                      cls.quarter,
                      cls.rep_period,
                      cls.next_rep_period,
                      cls.current_date,
                      cls.prev_date,
                      cls.next_date,
                      cls.t_curr_half_mean,
                      cls.t_curr_month_mean,
                      cls.t_curr_period_mean,
                      cls.shareprice,
                      cls.increase,
                      cls.t_half_month_increase,
                      cls.t_monthly_increase,
                      cls.t_next_half_mean,
                      cls.t_next_month_mean,
                      cls.t_next_period_mean,
                      cls.t_next_price,
                      cls.t_period_increase]

        return basic_tags

    @classmethod
    def desired_indicators(cls) -> list:
        tags2func = [
            cls.pricetobook,
            cls.pricetorevenue,
            cls.pricetoearnings,
            cls.dps2price,
            cls.dividendspayoutratio,
            cls.roe,
            cls.roa,
            cls.profitmargin,
            cls.debtratio,
            # cls.cashcoverageratio: lambda r: (),
            cls.currentratio]

        return tags2func
        # cls.eva: lambda r:
        # r[cls.roc - cls.costof] *

        # cls.pricetoearnings,
        # cls.dps2price,
        # cls.dividendpayout,
        # cls.roe,
        # cls.roa,
        # cls.eva}

    @classmethod
    def all(cls):
        # cls.price2book, cls.book2market, cls.fcf2equity, cls.fcf2commonequity])


        return list(set(cls.basic_tags()
                        + cls.income_statement
                        + cls.balance_sheet
                        + cls.cash_flow
                        + cls.calculations))
